services:
  - type: web
    name: cloudsec-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloudsec-db
          property: connectionString
      - key: SECRET_KEY
        value: 98dsfuh2389hf230f98hsdof23
